from __future__ import print_function

import sys
import cPickle
import pandas as pd
import numpy as np

from keras.preprocessing import sequence
from keras.preprocessing.text import Tokenizer
from keras.utils import np_utils

from sklearn.cross_validation import train_test_split
from sent_op import load_w2v, sents_3dtensor

def xcol_nninput_embd(textlist, nb_words, maxlen):
    """
    load textlist, which is corresponding to the text col in a DF
    :param textlist:
    :param nb_words:
    :param maxlen:
    :return:
    """
    # note that textlist was generated by df.txt.values.tolist()
    textraw = [line.encode('utf-8') for line in textlist]  # keras needs str
    # keras deals with tokens
    token = Tokenizer(nb_words=nb_words)
    token.fit_on_texts(textraw)
    xseq = token.texts_to_sequences(textraw)
    # padding
    xseq_padded = sequence.pad_sequences(xseq, maxlen=maxlen, padding='post', truncating='post')
    return(xseq_padded)


def pickled2df(pickfile):
    """
    read a pickled file and create a DF with two cols, label and text
    """
    print("loading %s" % pickfile)
    x = cPickle.load(open(pickfile, "rb"))
    revs, W, W2, word_idx_map, vocab = x[0], x[1], x[2], x[3], x[4]
    print("data loaded!")

    # focusing on revs.
    texts, labels = [], []
    for rev in revs:
        texts.append(rev["text"])
        labels.append(rev["y"])
    df = pd.DataFrame({'label': labels, 'text': texts})
    return df

def load_csvs(traincsv, testcsv, nb_words, maxlen):

    train_df = pd.read_csv(traincsv)
    test_df = pd.read_csv(testcsv)
    print(train_df.head())

    X_train = xcol_nninput_embd(train_df.text.values.tolist(), nb_words, maxlen)
    X_test  = xcol_nninput_embd(test_df.text.values.tolist(), nb_words, maxlen)

    train_y = train_df.label.values
    test_y  = test_df.label.values

    nb_classes = len(np.unique(train_y))
    Y_train = np_utils.to_categorical(train_y, nb_classes)
    Y_test = np_utils.to_categorical(test_y, nb_classes)

    print('X tensor shape: ', X_train.shape)
    print('Y tensor shape: ', Y_train.shape)
    return(X_train, Y_train, X_test, Y_test, nb_classes)


def load_asap():
    nb_words = 5000
    maxlen = 200
    X_train, Y_train, X_test, Y_test, nb_classes = load_csvs('../asap_sas/set1_train.csv',
                                                             '../asap_sas/set1_train.csv',
                                                             nb_words, maxlen)
    return(X_train, Y_train, X_test, Y_test, nb_classes)


def load_sg15():
    nb_words = 5000
    maxlen = 250
    X_train, Y_train, X_test, Y_test, nb_classes = load_csvs('data/train.csv',
                                                             'data/test.csv',
                                                             nb_words, maxlen)
    return(X_train, Y_train, X_test, Y_test, nb_classes)


def load_mr(embd_type):
    """
    :param embd_type: self vs. w2v
    :return:
    """
    maxlen = 200
    nb_words = 20000
    seed = 75513
    train_size = 0.8

    df = pickled2df('data/mr.p')
    print(df.head())

    np.random.seed(seed)
    train_X, test_X, train_y, test_y = train_test_split(df.text.values.tolist(),
                                                        df.label.values,
                                                        train_size=train_size, random_state=1)
    if(embd_type == 'self'):
        X_train = xcol_nninput_embd(train_X, nb_words, maxlen)
        X_test  = xcol_nninput_embd(test_X,  nb_words, maxlen)
    elif(embd_type == 'w2v'):
        w2v = load_w2v('data/Google_w2v.bin')
        print("loaded Google word2vec")
        nb_classes = len(np.unique(train_y))
        X_train = sents_3dtensor(train_X, maxlen, w2v)
        X_test  = sents_3dtensor(test_X, maxlen, w2v)
        Y_train = np_utils.to_categorical(train_y, nb_classes)
        Y_test  = np_utils.to_categorical(test_y, nb_classes)
    else:
        print('wrong embd_type')

    print('X tensor shape: ', X_train.shape)
    print('Y tensor shape: ', Y_train.shape)
    return (X_train, Y_train, X_test, Y_test, nb_classes)

def main():
    print('asap separate train and test')
    load_asap()
    print('='*50)

    print('sg15 separate train and test')
    load_sg15()
    print('='*50)

    print('mr single df')
    # load_mr('w2v')

if __name__=="__main__":
    main()
